# This file defines how to run the multi-container application.
# Run 'docker-compose up' to build and start both services.

version: '3.8'

services:
  # The Backend API Service
  backend:
    build:
      context: ./backend  # Tells Docker Compose to look for the Dockerfile in the 'backend' folder
    container_name: healthcare_backend_api
    restart: unless-stopped
    env_file:
      - ./backend/.env   # Passes your database credentials into the container
    ports:
      - "3001:3001"      # Maps your local port 3001 to the container's port 3001
    networks:
      - app-network

  # The Frontend Web Server Service
  frontend:
    build:
      context: ./healthcare-frontend # Tells Docker Compose to look for the Dockerfile in the 'frontend' folder
    container_name: healthcare_frontend_ui
    restart: unless-stopped
    ports:
      - "8080:80"        # Maps your local port 8080 to the container's Nginx port 80
    depends_on:
      - backend          # Tells Docker to wait for the backend to start before starting the frontend
    networks:
      - app-network

# Defines the network that allows containers to communicate with each other
networks:
  app-network:
    driver: bridge